# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38f77f24001c8bc4197c26187d220952536c9a6da91710c4347fd78d7c91aead12f539be2598d209be9cd5165de29c849544b6489b52ffa756e6ff12a9239b5

test:
  secret_key_base: 7bdb4398e85c23cea265861a18e601434da2549aeb68362b6f71dba82c95077fdc891382bbfb926fd418098c6e321881ee426cd2d5a362b1993bd62c7f8f58a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
